# FA Download configuration file

# Run a pprof debug server on http://localhost:6680/debug/pprof/
debug = false
logLevel = "INFO"
# For colors in log output, useful in IDEs that properly interpret them but don't show up as TTYs
logForceColors = true
# Output logs in JSON format instead. Overrides logForceColors.
logJSON = false

[fa]
# Proxy server to use for FA requests. You can do something like
# ssh -D 18080 my-awesome-server.com
# to run a SOCKS5 proxy over an ssh connection, and then specify something like
# socks5://127.0.0.1:18080
# for this to use that proxy.
proxy = ""
# You probably want to set this to what your browser says it is.
userAgent = "fadownload/faapi/go"
# Requests to FA will not occur more frequently than this.
# Note: Requests of facdn (for downloading images) are not constrained by this.
rateLimit = "10s"
# The maximum amount of time for a single request to FA, including any retries.
# This should be at least as long as requestTimeout times retryLimit.
timeout = "1m"
# The maximum amount of time for a single request attempt to FA.
requestTimeout = "15s"
# The delay between retries for a single request.
retryDelay = "5s"
# How many times to retry a single request, whether it timed out or got an error
# code back from FA or Cloudflare.
retryLimit = 3

# Cookies to set on requests to FA. If you don't provide valid cookies that will
# get you logged in to an account, only general-rated artwork will be returned.
[[fa.cookies]]
name = "a"
value = "A"

[[fa.cookies]]
name = "b"
value = "B"

